### PR TITLE
Fixing errors when removing from Arxiv PDFs

### PR DESCRIPTION
**Pull request by hudssntao**
Still need to address combining download & remove scripts, but creating PR now to see if @trigaten or @Mcilie has my tqdm error.

Fix uses tika instead of PyPDF2, parsing through all PDF text so it included more papers (1692 I believe)

### CODE REVIEW

**Comment by trigaten** [comment]
Is this ready for review?

**Comment by hudssntao** [comment]
Not yet, going to try and combine the two scripts first.

**Comment by hudssntao** [comment]
Ready for review.

**Review by Mcilie — COMMENTED** [review]
looks good

**Review by Mcilie — APPROVED** [review]

**Pull request merged**
